#ifndef PARSE_H
#define PARSE_H

#include "token.h"
#include <stdbool.h> // For bool type

/**
 * @brief Parses a list of tokens to check for valid syntax according to the grammar.
 * * @param tokens The array of tokens generated by the tokenizer.
 * @param token_count The number of tokens in the array.
 * @return true if the command syntax is valid, false otherwise.
 */
bool parse(token* tokens, int token_count);

#endif // PARSE_H